### PR TITLE
I like changes

### PR DESCRIPTION
**Pull request by diegocanton**
Would you like to comment on their contributions, but I'm still new to GIT and I do not know how to do it. I added you as a collaborator of the original code.
Thanks for the time, code and help.

### CODE REVIEW

**Comment by zanix** [comment]
Oh, I didn't realize someone was actually looking at my fork.
All this was done over the weekend, frantically trying to fix a few hundred radios at a wireless ISP before this 'virus' caused them to reset to defaults. They wanted to be able to log the action that were taken on each radio as well.

Since I first forked your repo, it looks like you made some of the same changes I did.
If you want some of my changes merged in, I could create a branch on my fork that is up to date with your master branch, then do a separate pull request with some of the changes I made.

**Comment by diegocanton** [comment]
Man, all improvement is welcome.

If you can, it would be of great help to the staff. I'm new in using GIT and I do not know how these things.

**Comment by zanix** [comment]
What would you like merged in?

**Comment by diegocanton** [comment]
Yes, it would be interesting for all these options LOG and other improvements.

**Comment by zanix** [comment]
Awesome, I will do a fresh fork and a pull request with my changes after work (which ends in 4 hours)

**Comment by zanix** [comment]
Going to close this since I will need to make a new one

**Pull request closed without merging**
